; DO NOT EDIT THIS FILE DIRECTLY.
; Changes may be lost if the file is updated from the Git repository.
; Make a copy of the file and name it 'files.iss'.
; Then, add the information relevant to your addin.

; Files are expected in the {#sourcedir} (see config.dist.iss).
; The destination folder is automatically determined; it resides in the
; user profile. See inc/code.iss for details.

; Example:
; Source: {#sourcedir}\myaddin.ini; DestDir: {code:GetDestDir}\

