; DO NOT EDIT THIS FILE DIRECTLY.
; Changes may be lost if the file is updated from the Git repository.
; Make a copy of the file in the parent folder and name it 'messages.iss'.
; Then, insert the information relevant to your addin.

; Example:
; Deutsch.ExcelNotInstalled=Excel ist nicht installiert
; When adding messages, make sure to also modify the languages.dist.iss
; file.


; vim: set ft=pascal ts=2 sts=2 sw=2 noet tw=60 fo+=lj cms=;%s 
