; DO NOT EDIT THIS FILE DIRECTLY.
; Changes may be lost if the file is updated from the Git repository.
; Make a copy of the file in the parent folder and name it 'tasks.iss'.
; Then, insert the information relevant to your addin.

